//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDUsingJquery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_data
    {
        public int sid { get; set; }
        public string sname { get; set; }
        public Nullable<int> sage { get; set; }
    }
}
