//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDUsingJquery.Models
{
    using System;
    
    public partial class USP_Get1AllEmployees_Result1
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<long> ROWNUMBER { get; set; }
    }
}
